apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-website'
  labels:
    katenary.io/component: website
    katenary.io/project: website
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: e809d58f811f27d44b71d80e169b728ea321f659
    katenary.io/version: 0.2.0-alpha2
spec:
  selector:
    katenary.io/component: website
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
